// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"iavra_text_sound","status":true,"description":"Dynamically plays sound effects, while text messages are printed.\r\n<Iavra Text Sound>","parameters":{"Enable Text Sounds":"true","Sound Name":"Cursor1","Sound Pan":"0","Sound Pitch":"80","Sound Volume":"10","Interval":"1","Limit":"-1"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"true","Custom Image":"Bijeg Games presents","Fade Out Time":"40","Fade In Time":"40","Wait Time":"40"}},
{"name":"LaserGenerator","status":true,"description":"","parameters":{}},
{"name":"GALV_EventSpawner","status":true,"description":"(v.1.8) Spawn events from a specified spawn map to a desired location.","parameters":{"Spawn Map Id":"2"}}
];
